# Generated by Django 5.2.8 on 2026-02-05 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='organ',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='organ',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patientmedicine',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='position',
        ),
        migrations.RemoveField(
            model_name='mrireport',
            name='organ_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tissue_type',
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='Cairo', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='enter your password', max_length=128),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('medical', 'Medical'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donormedicalprofile',
            name='organ_available',
            field=models.CharField(choices=[('kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lung', 'Lung'), ('Pancreas', 'Pancreas')], default='Kindy', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mrireport',
            name='after_scan',
            field=models.ImageField(blank=True, null=True, upload_to='mri/after/'),
        ),
        migrations.AlterField(
            model_name='mrireport',
            name='before_scan',
            field=models.ImageField(blank=True, null=True, upload_to='mri/before/'),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='ai_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='match_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='organmatching',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientmedicalprofile',
            name='organ_needed',
            field=models.CharField(choices=[('kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lung', 'Lung'), ('Pancreas', 'Pancreas')], default='Kindy', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.hospital'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to='core.doctor'),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='user_reports/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Organ',
        ),
        migrations.DeleteModel(
            name='PatientMedicine',
        ),
    ]
