# Generated by Django 5.2.8 on 2026-02-06 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_patientmedicine_medicine_remove_organ_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='operation_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SurgeryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_summary', models.TextField()),
                ('complications', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='surgery_reports/files/')),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='surgery_reports/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.surgery')),
            ],
        ),
    ]
