# Generated by Django 5.2.8 on 2026-02-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_surgery_duration_minutes_surgery_operation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryreport',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryreport',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryreport',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryreport',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryreport',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgeryreport',
            name='temperature_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('surgery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='core.surgeryreport')),
            ],
        ),
    ]
